### ISSUE TITLE
Nice project, i want to contribute

### ISSUE THREAD

**Issue by ali-s3** [wesleezz/NekoWorlds#1]
Hello stranger, i want to contribute in your project, i can add new features, pages or any kind of functionality as required for you, i'm doing this just because i like it without any money or charges, if yes let me know, thanks

**Comment by wesleezz** [comment]
okay u can contact me on discord Wesleezz#2122 or telegram @Wesleezz

Thank u for issue
Wesleezz - NekoWorlds

**Comment by ali-s3** [comment]
hi there first of all thank soo much for replying, i really love your
project and your style of project pages and components, im also well known
with react and nextjs but may be not proficient as much as you are, im sure
i can learn many things while working with you, i just sent you friend
request on discord, we will talk there soon, thanks again.

Regards
Ali
